name: CI

on:
    push:
        branches: [ master ]
    workflow_dispatch:

env:
    IMAGE_NAME: fablab-ledmatrix

jobs:
    build:
        name: Build & Publish
    
        runs-on: ubuntu-latest
        timeout-minutes: 10
    
        permissions:
            packages: write
            contents: read
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          
          - name: Log in to Registry
            run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
            with:
              platforms: 'linux/amd64,linux/arm64'
          
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          
          - name: Set up image tags
            id: vars
            run: |
              REPO_LOWERCASE=${GITHUB_REPOSITORY,,}
              IMAGE_NAME=ghcr.io/$REPO_LOWERCASE
              COMMIT_TAG=${GITHUB_SHA::7}
              echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
              echo "commit_tag=$COMMIT_TAG" >> $GITHUB_OUTPUT
          
          - name: Build and push
            id: docker_build
            uses: docker/build-push-action@v6
            with:
              context: .
              push: true
              tags: ${{ steps.vars.outputs.image_name }}:latest
              platforms: linux/amd64,linux/arm64
          
          - name: Image digest
            run: echo ${{ steps.docker_build.outputs.digest }}